services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - TZ=Africa/Tunis
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - WEBHOOK_URL=https://kirsten-unendable-jani.ngrok-free.dev
      - N8N_EDITOR_BASE_URL=https://kirsten-unendable-jani.ngrok-free.dev
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_TELEMETRY_DISABLED=true
      - N8N_PYTHON_ENABLE=true      # <- هذا مهم لتفعيل Python Node
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
